### ISSUE TITLE
[Bug] Clicking on a thermo in editor or solution mode

### ISSUE THREAD

**Issue by chennisden** [OctoPuzzles/octopuzzles#112] opened 2023-02-17 23:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If you click part of a square taken up by a thermo, the square will not be selected.

Workaround: use arrowkeys or aim the mouse at part of the square not occupied by the thermo.

For clarity, this is the VISUAL thermo you cannot click on, i.e. any pixel taken up by a thermo cannot be clicked.

I expect the square to be selected no matter if my mouse hits the thermo or not

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SorenHolstHansen** [comment] 2023-02-18 15:11
Thanks for finding this, and in general using the site! I think I have a fix for this

**Comment by SorenHolstHansen** [comment] 2023-02-18 15:24
@chennisden If you get the time, could you check to see if the problem is solved in https://website-pr-114.onrender.com/
I also added the ctrl+z and ctrl+y shortcuts if you want to try that as well

**Closed** 2023-02-19 13:41 UTC
Labels: bug
